version: '3.7'
services:
  web:
    build: ./Bad_drivers
    command: gunicorn bad_drivers.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Bad_drivers/:/usr/src/bad_drivers/
    ports:
      - 7000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    
    ports:
      - 5432:5432

volumes:
  postgres_data:

      
