version: '3.7'
services:
  web:
    build: ./Bad_drivers
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Bad_drivers/:/usr/src/bad_drivers/
    ports:
      - 7000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./init.sql:/var/lib/postgresql/data/

    restart: always
    environment:
      - POSTGRES_USER=nick_postgres
      - POSTGRES_PASSWORD=vfqythscjcen!!!11
      - POSTGRES_DB=postgres

    ports: 
      - 5432:5432

volumes:
  postgres_data:

      
