# Generated by Django 3.0.8 on 2020-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_reports_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivment_name', models.CharField(max_length=30)),
                ('achivment_description', models.TextField()),
                ('achivment_icon_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
