# Generated by Django 3.0.8 on 2020-08-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_achivments_achivment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivments',
            name='achivment_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
