# Generated by Django 3.1 on 2020-08-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200807_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualTokens',
        ),
    ]
