# Generated by Django 3.1 on 2020-08-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_actualtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivments',
            name='achivment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
