# Generated by Django 3.1 on 2020-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200817_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
