# Generated by Django 3.1.3 on 2020-12-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_reports_report_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report_picture',
            field=models.ImageField(upload_to='~/static/'),
        ),
    ]
