# Generated by Django 3.0.8 on 2020-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('reports_id', models.IntegerField()),
                ('achivments_id', models.IntegerField()),
                ('recieved_reports', models.IntegerField()),
                ('send_reports', models.IntegerField()),
                ('decline_reports', models.IntegerField()),
                ('processing_reports', models.IntegerField()),
            ],
        ),
    ]
