# Generated by Django 3.0.8 on 2020-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='achivments_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='decline_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='processing_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='recieved_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='reports_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
