# Generated by Django 3.0.8 on 2020-08-05 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200801_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivments',
            name='achivment_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Users'),
            preserve_default=False,
        ),
    ]
