# Generated by Django 3.1 on 2020-08-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200805_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achivments',
            options={'ordering': ['id', 'achivment_user_id', 'achivment_name', 'achivment_description', 'achivment_icon_id']},
        ),
    ]
