# Generated by Django 3.1 on 2020-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_actualtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtokens',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
