# Generated by Django 3.1 on 2020-08-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200815_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivments',
            name='achivment_user_id',
        ),
        migrations.AddField(
            model_name='achivments',
            name='achivment_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
