# Generated by Django 3.1 on 2020-08-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200815_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achivments',
            options={},
        ),
        migrations.RemoveField(
            model_name='achivments',
            name='achivment_user',
        ),
    ]
