# Generated by Django 3.1 on 2020-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_reports_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_picture',
            field=models.ImageField(default=None, upload_to='static/'),
            preserve_default=False,
        ),
    ]
