# Generated by Django 3.0.7 on 2020-12-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201205_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=15)),
                ('report_description', models.CharField(max_length=50)),
                ('report_picture', models.ImageField(upload_to='static/')),
                ('report_status', models.CharField(default='processing', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
