# Generated by Django 3.0.7 on 2020-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201205_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivments',
            new_name='Achivment',
        ),
    ]
