# Generated by Django 3.1 on 2020-08-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200815_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_real_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
