# Generated by Django 3.1.3 on 2020-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_report'),
    ]

    operations = [
        
    ]
