# Generated by Django 3.1.7 on 2021-03-17 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achivments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivments',
            new_name='Achivment',
        ),
        migrations.CreateModel(
            name='UserAchivment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('achivment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='achivments.achivment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
            },
        ),
    ]
