# Generated by Django 3.1.5 on 2021-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achivments', '0002_auto_20210317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivment',
            name='achivment_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
