# Generated by Django 3.1.3 on 2020-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201205_2144'),
    ]

    operations = [

    ]
