# Generated by Django 3.1.3 on 2020-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_report_car_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='report',
            name='image2',
            field=models.FileField(default=1, upload_to='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='image3',
            field=models.FileField(default=1, upload_to='.'),
            preserve_default=False,
        ),
    ]
