# Generated by Django 3.1.7 on 2021-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Жалобы', 'verbose_name_plural': 'Таблица жалоб'},
        ),
        migrations.AddField(
            model_name='report',
            name='image_1',
            field=models.ImageField(default=1, upload_to='cars'),
            preserve_default=False,
        ),
    ]
