# Generated by Django 3.1.7 on 2021-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210310_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_2',
            field=models.ImageField(default=1, height_field=400, upload_to='reports_images', width_field=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='image_3',
            field=models.ImageField(default=1, height_field=400, upload_to='reports_images', width_field=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='image_1',
            field=models.ImageField(height_field=400, upload_to='reports_images', width_field=400),
        ),
    ]
