# Generated by Django 3.1.7 on 2021-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210310_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_country',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.DateTimeField(default="2020-01-21 12:23"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='image_1',
            field=models.ImageField(upload_to='reports_images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_2',
            field=models.ImageField(upload_to='reports_images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_3',
            field=models.ImageField(upload_to='reports_images'),
        ),
    ]
