# Generated by Django 3.1.7 on 2021-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210313_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
