# Generated by Django 3.1.7 on 2021-03-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210316_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivment_name', models.CharField(max_length=20)),
                ('achivment_description', models.TextField()),
                ('achivment_image', models.ImageField(upload_to='achivments_images')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
    ]
