# Generated by Django 3.1.7 on 2021-03-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20210317_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achivments',
        ),
    ]
